#@ app_name = "klub-zmj-test"
#@ image = "auto0mat/klub-zmj-test:2025.420"
#@ config_map = "klub-zmj-test-env"
#@ secret_map = "klub-zmj-test-access"
#@ load("klub.lib.yml", "klub_web")
--- #@ klub_web(app_name, image, config_map, secret_map, 1, 1)
