#@ app_name = "ride-to-work-by-bike-backend-test"
#@ image = "auto0mat/dopracenakole:2026.2205"
#@ config_map = "ride-to-work-by-bike-backend-test-env"
#@ secret_map = "ride-to-work-by-bike-backend-test-access"
#@ load("dpnk.lib.yml", "web")
--- #@ web(app_name, image, config_map, secret_map, 1, 1)
