kind: ConfigMap
apiVersion: v1
metadata:
  name: ride-to-work-by-bike-frontend-test-env
  namespace: default
  managedFields:
    - manager: kubectl
      operation: Update
      apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        "f:data":
          .: {}
          "f:API_BASE": {}
          "f:URL_APP_DATA_PRIVACY_POLICY": {}
          "f:ENTRY_FEE_PAYMENT_OPTIONS": {}
          "f:URL_DONATE": {}
          "f:URL_RIDE_TO_WORK_BY_BIKE_OLD_FRONTEND_DJANGO_APP": {}
          "f:CHALLENGE_MONTH": {}
          "f:CHALLENGE_START_DATE": {}
data:
  API_BASE: "https://dpnk2019.dopracenakole.cz/rest/"
  URL_APP_DATA_PRIVACY_POLICY: "https://dopracenakole.cz/zasady"
  ENTRY_FEE_PAYMENT_OPTIONS: "850,1500"
  URL_DONATE: "https://auto-mat.cz/daruj-dopracenakole"
  URL_RIDE_TO_WORK_BY_BIKE_OLD_FRONTEND_DJANGO_APP: "https://dpnk2019.dopracenakole.cz"
  CHALLENGE_MONTH: "may"
  CHALLENGE_START_DATE: "2024-08-01T12:00:00"
  CHALLENGE_ALLOW_REGISTER_ORGANIZATION_ADMIN: "enable"
